title: Aliyun Cloud in Blog
logo: /assets/img/logo.png
description: Welcome to the Aliyun Cloud's Blog by Adisatya IT Consultant.
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
